version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_maiacampus
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maia_campus_event
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  node:
    build: ./express-server
    container_name: node_maiacampus
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: maia_campus_event
